# Form implementation generated from reading ui file 'caracteristicasView.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 400)
        MainWindow.setMinimumSize(QtCore.QSize(300, 400))
        MainWindow.setMaximumSize(QtCore.QSize(300, 400))
        MainWindow.setStyleSheet("background-color: rgb(235, 235, 239);\n"
"color: #1f1f1f;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(0, 50))
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalWidget_2.setObjectName("horizontalWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalWidget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBox = QtWidgets.QComboBox(parent=self.horizontalWidget_2)
        self.comboBox.setMinimumSize(QtCore.QSize(140, 0))
        self.comboBox.setMaximumSize(QtCore.QSize(140, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("QComboBox{\n"
"    color: black;\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_2.addWidget(self.comboBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(parent=self.horizontalWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.txtValor = QtWidgets.QLineEdit(parent=self.horizontalWidget_2)
        self.txtValor.setMinimumSize(QtCore.QSize(60, 0))
        self.txtValor.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtValor.setFont(font)
        self.txtValor.setStyleSheet("QLineEdit{\n"
"    color: black;\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"}\n"
"")
        self.txtValor.setObjectName("txtValor")
        self.horizontalLayout_2.addWidget(self.txtValor)
        self.verticalLayout.addWidget(self.horizontalWidget_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnAgregarCaracteristica = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnAgregarCaracteristica.setMinimumSize(QtCore.QSize(20, 20))
        self.btnAgregarCaracteristica.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnAgregarCaracteristica.setFont(font)
        self.btnAgregarCaracteristica.setStyleSheet("QPushButton{\n"
"    color: black;\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: #3081D0;\n"
"    color: white;\n"
"}")
        self.btnAgregarCaracteristica.setObjectName("btnAgregarCaracteristica")
        self.horizontalLayout_3.addWidget(self.btnAgregarCaracteristica)
        self.btnQuitarCaracteristica = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnQuitarCaracteristica.setMinimumSize(QtCore.QSize(20, 20))
        self.btnQuitarCaracteristica.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnQuitarCaracteristica.setFont(font)
        self.btnQuitarCaracteristica.setStyleSheet("QPushButton{\n"
"    color: black;\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: #3081D0;\n"
"    color: white;\n"
"}")
        self.btnQuitarCaracteristica.setObjectName("btnQuitarCaracteristica")
        self.horizontalLayout_3.addWidget(self.btnQuitarCaracteristica)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.tblCaracteristicas = QtWidgets.QTableWidget(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tblCaracteristicas.setFont(font)
        self.tblCaracteristicas.setStyleSheet("QTableWidget{\n"
"    color: black;\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"}")
        self.tblCaracteristicas.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tblCaracteristicas.setObjectName("tblCaracteristicas")
        self.tblCaracteristicas.setColumnCount(3)
        self.tblCaracteristicas.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblCaracteristicas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblCaracteristicas.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblCaracteristicas.setHorizontalHeaderItem(2, item)
        self.tblCaracteristicas.horizontalHeader().setDefaultSectionSize(90)
        self.tblCaracteristicas.horizontalHeader().setMinimumSectionSize(30)
        self.tblCaracteristicas.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.tblCaracteristicas)
        self.horizontalWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalWidget.setMinimumSize(QtCore.QSize(0, 30))
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.btnAceptar = QtWidgets.QPushButton(parent=self.horizontalWidget)
        self.btnAceptar.setMinimumSize(QtCore.QSize(100, 25))
        self.btnAceptar.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnAceptar.setFont(font)
        self.btnAceptar.setStyleSheet("QPushButton{\n"
"    color: black;\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: #3081D0;\n"
"    color: white;\n"
"}")
        self.btnAceptar.setObjectName("btnAceptar")
        self.horizontalLayout.addWidget(self.btnAceptar)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.btnCancelar = QtWidgets.QPushButton(parent=self.horizontalWidget)
        self.btnCancelar.setMinimumSize(QtCore.QSize(100, 25))
        self.btnCancelar.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnCancelar.setFont(font)
        self.btnCancelar.setStyleSheet("QPushButton{\n"
"    color: black;\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: #3081D0;\n"
"    color: white;\n"
"}")
        self.btnCancelar.setObjectName("btnCancelar")
        self.horizontalLayout.addWidget(self.btnCancelar)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout.addWidget(self.horizontalWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Características"))
        self.label_2.setText(_translate("MainWindow", "Valor"))
        self.btnAgregarCaracteristica.setText(_translate("MainWindow", "+"))
        self.btnQuitarCaracteristica.setText(_translate("MainWindow", "-"))
        item = self.tblCaracteristicas.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tblCaracteristicas.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Descripcion"))
        item = self.tblCaracteristicas.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Valor"))
        self.btnAceptar.setText(_translate("MainWindow", "Aceptar"))
        self.btnCancelar.setText(_translate("MainWindow", "Cancelar"))
