# Form implementation generated from reading ui file 'contratosView.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 400)
        MainWindow.setStyleSheet("background-color: rgb(235, 235, 239);\n"
"color: #1f1f1f;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(0, 60))
        self.label.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_9 = QtWidgets.QLabel(parent=self.horizontalWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.comboBox = QtWidgets.QComboBox(parent=self.horizontalWidget)
        self.comboBox.setMinimumSize(QtCore.QSize(120, 0))
        self.comboBox.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("QComboBox{\n"
"    color: black;\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        self.verticalLayout.addWidget(self.horizontalWidget, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.formWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.formWidget.setObjectName("formWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formWidget)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.formLayout_2.setObjectName("formLayout_2")
        self.lblFechaInicio = QtWidgets.QLabel(parent=self.formWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblFechaInicio.setFont(font)
        self.lblFechaInicio.setObjectName("lblFechaInicio")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblFechaInicio)
        self.dateInicioContrato = QtWidgets.QDateEdit(parent=self.formWidget)
        self.dateInicioContrato.setMinimumSize(QtCore.QSize(300, 0))
        self.dateInicioContrato.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateInicioContrato.setFont(font)
        self.dateInicioContrato.setStyleSheet("QDateEdit{\n"
"    color: black;\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"}")
        self.dateInicioContrato.setCalendarPopup(True)
        self.dateInicioContrato.setObjectName("dateInicioContrato")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.dateInicioContrato)
        self.lblFechaFin = QtWidgets.QLabel(parent=self.formWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblFechaFin.setFont(font)
        self.lblFechaFin.setObjectName("lblFechaFin")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblFechaFin)
        self.dateFinContrato = QtWidgets.QDateEdit(parent=self.formWidget)
        self.dateFinContrato.setMinimumSize(QtCore.QSize(300, 0))
        self.dateFinContrato.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateFinContrato.setFont(font)
        self.dateFinContrato.setStyleSheet("QDateEdit{\n"
"    color: black;\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"}")
        self.dateFinContrato.setCalendarPopup(True)
        self.dateFinContrato.setObjectName("dateFinContrato")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.dateFinContrato)
        self.label_4 = QtWidgets.QLabel(parent=self.formWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.txtValor = QtWidgets.QLineEdit(parent=self.formWidget)
        self.txtValor.setMinimumSize(QtCore.QSize(300, 0))
        self.txtValor.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtValor.setFont(font)
        self.txtValor.setStyleSheet("QLineEdit{\n"
"    color: black;\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"}")
        self.txtValor.setObjectName("txtValor")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtValor)
        self.label_6 = QtWidgets.QLabel(parent=self.formWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_6)
        self.txtComision = QtWidgets.QLineEdit(parent=self.formWidget)
        self.txtComision.setMinimumSize(QtCore.QSize(300, 0))
        self.txtComision.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtComision.setFont(font)
        self.txtComision.setStyleSheet("QLineEdit{\n"
"    color: black;\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"}")
        self.txtComision.setObjectName("txtComision")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtComision)
        self.label_5 = QtWidgets.QLabel(parent=self.formWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cbxClientes = QtWidgets.QComboBox(parent=self.formWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cbxClientes.setFont(font)
        self.cbxClientes.setStyleSheet("QComboBox{\n"
"    color: black;\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"}")
        self.cbxClientes.setObjectName("cbxClientes")
        self.horizontalLayout_4.addWidget(self.cbxClientes)
        self.btnIngresarCliente = QtWidgets.QPushButton(parent=self.formWidget)
        self.btnIngresarCliente.setMinimumSize(QtCore.QSize(70, 0))
        self.btnIngresarCliente.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnIngresarCliente.setFont(font)
        self.btnIngresarCliente.setStyleSheet("QPushButton{\n"
"    color: black;\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: #3081D0;\n"
"    color: white;\n"
"}")
        self.btnIngresarCliente.setObjectName("btnIngresarCliente")
        self.horizontalLayout_4.addWidget(self.btnIngresarCliente)
        self.formLayout_2.setLayout(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout_4)
        self.label_7 = QtWidgets.QLabel(parent=self.formWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(parent=self.formWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_8)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cbxInmuebles = QtWidgets.QComboBox(parent=self.formWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cbxInmuebles.setFont(font)
        self.cbxInmuebles.setStyleSheet("QComboBox{\n"
"    color: black;\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"}")
        self.cbxInmuebles.setObjectName("cbxInmuebles")
        self.horizontalLayout_5.addWidget(self.cbxInmuebles)
        self.btnIngresarInmueble = QtWidgets.QPushButton(parent=self.formWidget)
        self.btnIngresarInmueble.setMinimumSize(QtCore.QSize(70, 0))
        self.btnIngresarInmueble.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnIngresarInmueble.setFont(font)
        self.btnIngresarInmueble.setStyleSheet("QPushButton{\n"
"    color: black;\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: #3081D0;\n"
"    color: white;\n"
"}")
        self.btnIngresarInmueble.setObjectName("btnIngresarInmueble")
        self.horizontalLayout_5.addWidget(self.btnIngresarInmueble)
        self.formLayout_2.setLayout(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.cbxAgentes = QtWidgets.QComboBox(parent=self.formWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cbxAgentes.setFont(font)
        self.cbxAgentes.setStyleSheet("QComboBox{\n"
"    color: black;\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"}")
        self.cbxAgentes.setObjectName("cbxAgentes")
        self.horizontalLayout_6.addWidget(self.cbxAgentes)
        self.formLayout_2.setLayout(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout_6)
        self.verticalLayout.addWidget(self.formWidget, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.btnConfirmar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnConfirmar.setMinimumSize(QtCore.QSize(100, 25))
        self.btnConfirmar.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setFamily("Bitstream Charter")
        font.setPointSize(12)
        self.btnConfirmar.setFont(font)
        self.btnConfirmar.setStyleSheet("QPushButton{\n"
"    color: black;\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: #3081D0;\n"
"    color: white;\n"
"}")
        self.btnConfirmar.setObjectName("btnConfirmar")
        self.verticalLayout.addWidget(self.btnConfirmar, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.btnSalir = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSalir.setMinimumSize(QtCore.QSize(100, 25))
        self.btnSalir.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnSalir.setFont(font)
        self.btnSalir.setStyleSheet("QPushButton{\n"
"    color: black;\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: #3081D0;\n"
"    color: white;\n"
"}")
        self.btnSalir.setObjectName("btnSalir")
        self.verticalLayout.addWidget(self.btnSalir, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Contratos"))
        self.label_9.setText(_translate("MainWindow", "Tipo de contrato"))
        self.lblFechaInicio.setText(_translate("MainWindow", "Fecha de Inicio"))
        self.lblFechaFin.setText(_translate("MainWindow", "Fecha de Fin"))
        self.label_4.setText(_translate("MainWindow", "Valor"))
        self.label_6.setText(_translate("MainWindow", "Comisión"))
        self.label_5.setText(_translate("MainWindow", "Cliente"))
        self.btnIngresarCliente.setText(_translate("MainWindow", "Ingresar"))
        self.label_7.setText(_translate("MainWindow", "Inmueble"))
        self.label_8.setText(_translate("MainWindow", "Agente"))
        self.btnIngresarInmueble.setText(_translate("MainWindow", "Ingresar"))
        self.btnConfirmar.setText(_translate("MainWindow", "Confirmar"))
        self.btnSalir.setText(_translate("MainWindow", "Salir"))
