# Form implementation generated from reading ui file 'contratosView.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 400)
        MainWindow.setStyleSheet("background-color: rgb(235, 235, 239);\n"
"color: #1f1f1f;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(parent=self.tab)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.formularioCompra = QtWidgets.QFormLayout()
        self.formularioCompra.setObjectName("formularioCompra")
        self.label_4 = QtWidgets.QLabel(parent=self.tab)
        self.label_4.setObjectName("label_4")
        self.formularioCompra.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(parent=self.tab)
        self.label_5.setObjectName("label_5")
        self.formularioCompra.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(parent=self.tab)
        self.label_6.setObjectName("label_6")
        self.formularioCompra.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_6)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.tab)
        self.lineEdit.setObjectName("lineEdit")
        self.formularioCompra.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.tab)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formularioCompra.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.tab)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formularioCompra.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_3)
        self.verticalLayout_3.addLayout(self.formularioCompra)
        self.btnComprar = QtWidgets.QPushButton(parent=self.tab)
        self.btnComprar.setMinimumSize(QtCore.QSize(100, 25))
        self.btnComprar.setMaximumSize(QtCore.QSize(100, 25))
        self.btnComprar.setStyleSheet("QPushButton{\n"
"    color: black;\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: #3081D0;\n"
"    color: white;\n"
"}")
        self.btnComprar.setObjectName("btnComprar")
        self.verticalLayout_3.addWidget(self.btnComprar)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.formularioVenta = QtWidgets.QFormLayout()
        self.formularioVenta.setObjectName("formularioVenta")
        self.label_7 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_7.setObjectName("label_7")
        self.formularioVenta.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_7)
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=self.tab_2)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formularioVenta.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_5)
        self.label_8 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_8.setObjectName("label_8")
        self.formularioVenta.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_8)
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.tab_2)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formularioVenta.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_4)
        self.label_9 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_9.setObjectName("label_9")
        self.formularioVenta.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_9)
        self.lineEdit_6 = QtWidgets.QLineEdit(parent=self.tab_2)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.formularioVenta.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_6)
        self.verticalLayout_2.addLayout(self.formularioVenta)
        self.btnVender = QtWidgets.QPushButton(parent=self.tab_2)
        self.btnVender.setMinimumSize(QtCore.QSize(100, 25))
        self.btnVender.setMaximumSize(QtCore.QSize(100, 25))
        self.btnVender.setStyleSheet("QPushButton{\n"
"    color: black;\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: #3081D0;\n"
"    color: white;\n"
"}")
        self.btnVender.setObjectName("btnVender")
        self.verticalLayout_2.addWidget(self.btnVender)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.btnSalir = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSalir.setMinimumSize(QtCore.QSize(100, 25))
        self.btnSalir.setMaximumSize(QtCore.QSize(100, 25))
        self.btnSalir.setStyleSheet("QPushButton{\n"
"    color: black;\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: #3081D0;\n"
"    color: white;\n"
"}")
        self.btnSalir.setObjectName("btnSalir")
        self.verticalLayout.addWidget(self.btnSalir)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Contratos"))
        self.label_3.setText(_translate("MainWindow", "Contrato de compra"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.btnComprar.setText(_translate("MainWindow", "Confirmar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Compra"))
        self.label_2.setText(_translate("MainWindow", "Contrato de venta"))
        self.label_7.setText(_translate("MainWindow", "TextLabel"))
        self.label_8.setText(_translate("MainWindow", "TextLabel"))
        self.label_9.setText(_translate("MainWindow", "TextLabel"))
        self.btnVender.setText(_translate("MainWindow", "Confirmar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Venta"))
        self.btnSalir.setText(_translate("MainWindow", "Salir"))
