# Form implementation generated from reading ui file 'formInmuebles.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 400)
        MainWindow.setStyleSheet("background-color: rgb(235, 235, 239);\n"
"color: #1f1f1f;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.formulario = QtWidgets.QFormLayout()
        self.formulario.setObjectName("formulario")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.formulario.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.formulario.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit)
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.formulario.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.formulario.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.formulario.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.formulario.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.formulario.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.formulario.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_8)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formulario.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formulario.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formulario.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formulario.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_5)
        self.lineEdit_6 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.formulario.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_6)
        self.lineEdit_7 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.formulario.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_7)
        self.verticalLayout.addLayout(self.formulario)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.btnAceptar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnAceptar.setMinimumSize(QtCore.QSize(100, 25))
        self.btnAceptar.setMaximumSize(QtCore.QSize(100, 25))
        self.btnAceptar.setStyleSheet("QPushButton{\n"
"    color: black;\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: #3081D0;\n"
"    color: white;\n"
"}")
        self.btnAceptar.setObjectName("btnAceptar")
        self.horizontalLayout_4.addWidget(self.btnAceptar)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.btnCancelar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCancelar.setMinimumSize(QtCore.QSize(100, 25))
        self.btnCancelar.setMaximumSize(QtCore.QSize(100, 25))
        self.btnCancelar.setStyleSheet("QPushButton{\n"
"    color: black;\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: #3081D0;\n"
"    color: white;\n"
"}")
        self.btnCancelar.setObjectName("btnCancelar")
        self.horizontalLayout_4.addWidget(self.btnCancelar)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Inmueble"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.label_7.setText(_translate("MainWindow", "TextLabel"))
        self.label_8.setText(_translate("MainWindow", "TextLabel"))
        self.btnAceptar.setText(_translate("MainWindow", "Aceptar"))
        self.btnCancelar.setText(_translate("MainWindow", "Cancelar"))
