# Form implementation generated from reading ui file 'formInmuebles.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 300)
        MainWindow.setStyleSheet("background-color: rgb(235, 235, 239);\n"
"color: #1f1f1f;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.form = QtWidgets.QWidget(parent=self.centralwidget)
        self.form.setObjectName("form")
        self.formulario = QtWidgets.QFormLayout(self.form)
        self.formulario.setLabelAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.formulario.setFormAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.formulario.setObjectName("formulario")
        self.label_2 = QtWidgets.QLabel(parent=self.form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formulario.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.txtNombre = QtWidgets.QLineEdit(parent=self.form)
        self.txtNombre.setMinimumSize(QtCore.QSize(300, 0))
        self.txtNombre.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtNombre.setFont(font)
        self.txtNombre.setStyleSheet("QLineEdit{\n"
"    color: black;\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"}")
        self.txtNombre.setObjectName("txtNombre")
        self.formulario.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtNombre)
        self.label_3 = QtWidgets.QLabel(parent=self.form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formulario.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.txtDireccion = QtWidgets.QLineEdit(parent=self.form)
        self.txtDireccion.setMinimumSize(QtCore.QSize(300, 0))
        self.txtDireccion.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtDireccion.setFont(font)
        self.txtDireccion.setStyleSheet("QLineEdit{\n"
"    color: black;\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"}")
        self.txtDireccion.setObjectName("txtDireccion")
        self.formulario.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtDireccion)
        self.label_4 = QtWidgets.QLabel(parent=self.form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formulario.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.txtSector = QtWidgets.QLineEdit(parent=self.form)
        self.txtSector.setMinimumSize(QtCore.QSize(300, 0))
        self.txtSector.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtSector.setFont(font)
        self.txtSector.setStyleSheet("QLineEdit{\n"
"    color: black;\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"}")
        self.txtSector.setObjectName("txtSector")
        self.formulario.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtSector)
        self.label_6 = QtWidgets.QLabel(parent=self.form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formulario.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_6)
        self.txtArea = QtWidgets.QLineEdit(parent=self.form)
        self.txtArea.setMinimumSize(QtCore.QSize(300, 0))
        self.txtArea.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtArea.setFont(font)
        self.txtArea.setStyleSheet("QLineEdit{\n"
"    color: black;\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"}")
        self.txtArea.setObjectName("txtArea")
        self.formulario.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtArea)
        self.label_8 = QtWidgets.QLabel(parent=self.form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formulario.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_8)
        self.txtTipo = QtWidgets.QLineEdit(parent=self.form)
        self.txtTipo.setMinimumSize(QtCore.QSize(300, 0))
        self.txtTipo.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtTipo.setFont(font)
        self.txtTipo.setStyleSheet("QLineEdit{\n"
"    color: black;\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"}")
        self.txtTipo.setObjectName("txtTipo")
        self.formulario.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtTipo)
        self.label_5 = QtWidgets.QLabel(parent=self.form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formulario.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)
        self.btnCaracteristicas = QtWidgets.QPushButton(parent=self.form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnCaracteristicas.setFont(font)
        self.btnCaracteristicas.setStyleSheet("QPushButton{\n"
"    color: black;\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: #3081D0;\n"
"    color: white;\n"
"}")
        self.btnCaracteristicas.setObjectName("btnCaracteristicas")
        self.formulario.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.btnCaracteristicas)
        self.verticalLayout.addWidget(self.form, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.btnAceptar = QtWidgets.QPushButton(parent=self.widget)
        self.btnAceptar.setMinimumSize(QtCore.QSize(100, 25))
        self.btnAceptar.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnAceptar.setFont(font)
        self.btnAceptar.setStyleSheet("QPushButton{\n"
"    color: black;\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: #3081D0;\n"
"    color: white;\n"
"}")
        self.btnAceptar.setObjectName("btnAceptar")
        self.horizontalLayout_4.addWidget(self.btnAceptar)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.btnCancelar = QtWidgets.QPushButton(parent=self.widget)
        self.btnCancelar.setMinimumSize(QtCore.QSize(100, 25))
        self.btnCancelar.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnCancelar.setFont(font)
        self.btnCancelar.setStyleSheet("QPushButton{\n"
"    color: black;\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: #3081D0;\n"
"    color: white;\n"
"}")
        self.btnCancelar.setObjectName("btnCancelar")
        self.horizontalLayout_4.addWidget(self.btnCancelar)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Inmueble"))
        self.label_2.setText(_translate("MainWindow", "Nombre"))
        self.label_3.setText(_translate("MainWindow", "Dirección"))
        self.label_4.setText(_translate("MainWindow", "Sector"))
        self.label_6.setText(_translate("MainWindow", "Área"))
        self.label_8.setText(_translate("MainWindow", "Tipo"))
        self.label_5.setText(_translate("MainWindow", "Características"))
        self.btnCaracteristicas.setText(_translate("MainWindow", "Elegir características"))
        self.btnAceptar.setText(_translate("MainWindow", "Aceptar"))
        self.btnCancelar.setText(_translate("MainWindow", "Cancelar"))
