# Form implementation generated from reading ui file 'mainView.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 500)
        MainWindow.setStyleSheet("background-color: rgb(235, 235, 239);\n"
"color: #1f1f1f;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(0, 60))
        self.label.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("DejaVu Serif Condensed")
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnEmpleados = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnEmpleados.setMinimumSize(QtCore.QSize(80, 230))
        self.btnEmpleados.setMaximumSize(QtCore.QSize(180, 230))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btnEmpleados.setFont(font)
        self.btnEmpleados.setStyleSheet("QPushButton{\n"
"    color: black;\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: #3081D0;\n"
"    color: white;\n"
"}")
        self.btnEmpleados.setObjectName("btnEmpleados")
        self.horizontalLayout.addWidget(self.btnEmpleados)
        self.btnContratos = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnContratos.setMaximumSize(QtCore.QSize(180, 230))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btnContratos.setFont(font)
        self.btnContratos.setStyleSheet("QPushButton{\n"
"    color: black;\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: #3081D0;\n"
"    color: white;\n"
"}")
        self.btnContratos.setObjectName("btnContratos")
        self.horizontalLayout.addWidget(self.btnContratos)
        self.btnReportes = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnReportes.setMaximumSize(QtCore.QSize(180, 230))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btnReportes.setFont(font)
        self.btnReportes.setStyleSheet("QPushButton{\n"
"    color: black;\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: #3081D0;\n"
"    color: white;\n"
"}")
        self.btnReportes.setObjectName("btnReportes")
        self.horizontalLayout.addWidget(self.btnReportes)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalWidget_2.setMaximumSize(QtCore.QSize(16777215, 60))
        self.horizontalWidget_2.setStyleSheet("background-color: #3f3f3f;\n"
"color: #f1f1f1;")
        self.horizontalWidget_2.setObjectName("horizontalWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalWidget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.horizontalWidget_2)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.horizontalWidget_2)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(parent=self.horizontalWidget_2)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout.addWidget(self.horizontalWidget_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Agencia Inmobiliaria "))
        self.btnEmpleados.setText(_translate("MainWindow", "Empleados"))
        self.btnContratos.setText(_translate("MainWindow", "Contratos"))
        self.btnReportes.setText(_translate("MainWindow", "Reportes"))
        self.label_2.setText(_translate("MainWindow", "Av. Gonzalez Suarez y Av. Loja"))
        self.label_3.setText(_translate("MainWindow", "Leandro gay"))
        self.label_4.setText(_translate("MainWindow", "El que este libre de pecado que tire la primera piedra"))
