# Form implementation generated from reading ui file 'reportesView.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 400)
        MainWindow.setStyleSheet("background-color: rgb(235, 235, 239);\n"
"color: #1f1f1f;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.cbxTipoReporte = QtWidgets.QComboBox(parent=self.widget)
        self.cbxTipoReporte.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cbxTipoReporte.setFont(font)
        self.cbxTipoReporte.setStyleSheet("QComboBox{\n"
"    color: black;\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"}\n"
"")
        self.cbxTipoReporte.setObjectName("cbxTipoReporte")
        self.cbxTipoReporte.addItem("")
        self.cbxTipoReporte.addItem("")
        self.cbxTipoReporte.addItem("")
        self.cbxTipoReporte.addItem("")
        self.cbxTipoReporte.addItem("")
        self.horizontalLayout.addWidget(self.cbxTipoReporte)
        self.verticalLayout.addWidget(self.widget, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.widget1 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblInmuebleElegido = QtWidgets.QLabel(parent=self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblInmuebleElegido.setFont(font)
        self.lblInmuebleElegido.setObjectName("lblInmuebleElegido")
        self.horizontalLayout_2.addWidget(self.lblInmuebleElegido)
        self.cbxTipoInmueble = QtWidgets.QComboBox(parent=self.widget1)
        self.cbxTipoInmueble.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cbxTipoInmueble.setFont(font)
        self.cbxTipoInmueble.setStyleSheet("QComboBox{\n"
"    color: black;\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"}")
        self.cbxTipoInmueble.setObjectName("cbxTipoInmueble")
        self.horizontalLayout_2.addWidget(self.cbxTipoInmueble)
        self.verticalLayout.addWidget(self.widget1, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.lbl_fecha_inicio = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_fecha_inicio.setFont(font)
        self.lbl_fecha_inicio.setObjectName("lbl_fecha_inicio")
        self.horizontalLayout_3.addWidget(self.lbl_fecha_inicio)
        self.dateInicio = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.dateInicio.setMinimumSize(QtCore.QSize(100, 0))
        self.dateInicio.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateInicio.setFont(font)
        self.dateInicio.setStyleSheet("QDateEdit{\n"
"    color: black;\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"}\n"
"")
        self.dateInicio.setCalendarPopup(True)
        self.dateInicio.setObjectName("dateInicio")
        self.horizontalLayout_3.addWidget(self.dateInicio)
        spacerItem1 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.lbl_fecha_fin = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_fecha_fin.setFont(font)
        self.lbl_fecha_fin.setObjectName("lbl_fecha_fin")
        self.horizontalLayout_3.addWidget(self.lbl_fecha_fin)
        self.dateFin = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.dateFin.setMinimumSize(QtCore.QSize(100, 0))
        self.dateFin.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateFin.setFont(font)
        self.dateFin.setStyleSheet("QDateEdit{\n"
"    color: black;\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"}\n"
"")
        self.dateFin.setCalendarPopup(True)
        self.dateFin.setObjectName("dateFin")
        self.horizontalLayout_3.addWidget(self.dateFin)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.tblReportes = QtWidgets.QTableWidget(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tblReportes.setFont(font)
        self.tblReportes.setStyleSheet("QTableWidget{\n"
"    color: black;\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"}")
        self.tblReportes.setObjectName("tblReportes")
        self.tblReportes.setColumnCount(0)
        self.tblReportes.setRowCount(0)
        self.tblReportes.horizontalHeader().setDefaultSectionSize(100)
        self.tblReportes.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.tblReportes)
        self.btnSalir = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSalir.setMinimumSize(QtCore.QSize(100, 25))
        self.btnSalir.setMaximumSize(QtCore.QSize(100, 25))
        self.btnSalir.setStyleSheet("QPushButton{\n"
"    color: black;\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: #3081D0;\n"
"    color: white;\n"
"}")
        self.btnSalir.setObjectName("btnSalir")
        self.verticalLayout.addWidget(self.btnSalir, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Reportes"))
        self.label_2.setText(_translate("MainWindow", "Filtro"))
        self.cbxTipoReporte.setItemText(0, _translate("MainWindow", "Ventas por agente"))
        self.cbxTipoReporte.setItemText(1, _translate("MainWindow", "Inmuebles de un tipo especifico"))
        self.cbxTipoReporte.setItemText(2, _translate("MainWindow", "Inmuebles vendidos por sector"))
        self.cbxTipoReporte.setItemText(3, _translate("MainWindow", "Inmuebles disponibles para la venta"))
        self.cbxTipoReporte.setItemText(4, _translate("MainWindow", "Ventas en un rango de fechas"))
        self.lblInmuebleElegido.setText(_translate("MainWindow", "Tipo"))
        self.lbl_fecha_inicio.setText(_translate("MainWindow", "Fecha inicial"))
        self.lbl_fecha_fin.setText(_translate("MainWindow", "Fecha final"))
        self.btnSalir.setText(_translate("MainWindow", "Salir"))
