# Form implementation generated from reading ui file 'reportesView.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 400)
        MainWindow.setStyleSheet("background-color: rgb(235, 235, 239);\n"
"color: #1f1f1f;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.cbxTipoReporte = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cbxTipoReporte.setStyleSheet("QComboBox{\n"
"    color: black;\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"}\n"
"")
        self.cbxTipoReporte.setObjectName("cbxTipoReporte")
        self.cbxTipoReporte.addItem("")
        self.cbxTipoReporte.addItem("")
        self.cbxTipoReporte.addItem("")
        self.cbxTipoReporte.addItem("")
        self.cbxTipoReporte.addItem("")
        self.horizontalLayout.addWidget(self.cbxTipoReporte)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_inmueble_elegido = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_inmueble_elegido.setObjectName("lbl_inmueble_elegido")
        self.horizontalLayout_2.addWidget(self.lbl_inmueble_elegido)
        self.cbx_inmueble_elegido = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cbx_inmueble_elegido.setStyleSheet("QComboBox{\n"
"    color: black;\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"}\n"
"")
        self.cbx_inmueble_elegido.setObjectName("cbx_inmueble_elegido")
        self.horizontalLayout_2.addWidget(self.cbx_inmueble_elegido)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl_fecha_inicio = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_fecha_inicio.setObjectName("lbl_fecha_inicio")
        self.horizontalLayout_3.addWidget(self.lbl_fecha_inicio)
        self.date_inicio = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.date_inicio.setStyleSheet("QDateEdit{\n"
"    color: black;\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"}\n"
"")
        self.date_inicio.setObjectName("date_inicio")
        self.horizontalLayout_3.addWidget(self.date_inicio)
        self.lbl_fecha_fin = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_fecha_fin.setObjectName("lbl_fecha_fin")
        self.horizontalLayout_3.addWidget(self.lbl_fecha_fin)
        self.date_fin = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.date_fin.setStyleSheet("QDateEdit{\n"
"    color: black;\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"}\n"
"")
        self.date_fin.setObjectName("date_fin")
        self.horizontalLayout_3.addWidget(self.date_fin)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.tblReportes = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tblReportes.setObjectName("tblReportes")
        self.tblReportes.setColumnCount(0)
        self.tblReportes.setRowCount(0)
        self.verticalLayout.addWidget(self.tblReportes)
        self.btnSalir = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSalir.setMinimumSize(QtCore.QSize(100, 25))
        self.btnSalir.setMaximumSize(QtCore.QSize(100, 25))
        self.btnSalir.setStyleSheet("QPushButton{\n"
"    color: black;\n"
"    background-color: white;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color: #3081D0;\n"
"    color: white;\n"
"}")
        self.btnSalir.setObjectName("btnSalir")
        self.verticalLayout.addWidget(self.btnSalir)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Reportes"))
        self.label_2.setText(_translate("MainWindow", "Filtro"))
        self.cbxTipoReporte.setItemText(0, _translate("MainWindow", "Ventas por agente"))
        self.cbxTipoReporte.setItemText(1, _translate("MainWindow", "Inmuebles de un tipo especifico"))
        self.cbxTipoReporte.setItemText(2, _translate("MainWindow", "Inmuebles vendidos por sector"))
        self.cbxTipoReporte.setItemText(3, _translate("MainWindow", "Inmuebles disponibles para la venta"))
        self.cbxTipoReporte.setItemText(4, _translate("MainWindow", "Ventas en un rango de fechas"))
        self.lbl_inmueble_elegido.setText(_translate("MainWindow", "Inmueble"))
        self.lbl_fecha_inicio.setText(_translate("MainWindow", "Fecha inicial"))
        self.lbl_fecha_fin.setText(_translate("MainWindow", "Fecha final"))
        self.btnSalir.setText(_translate("MainWindow", "Salir"))
